#!/data/data/com.termux/files/usr/bin/sh
set -a
. "$HOME/phone-server/.secrets/boot.env"
set +a

exec su -c "$BIN_DIR/AdGuardHome -c $DATA_DIR/AdGuardHome/AdGuardHome.yaml -w $DATA_DIR/AdGuardHome/ --no-check-update >> $LOG_DIR/adguard.log 2>&1"
