#!/data/data/com.termux/files/usr/bin/sh
. "$HOME/phone-server/.secrets/boot.env"
. "$HOME/phone-server/.secrets/glance.env"
sv check AdGuardHome || exit 1

exec env SSL_CERT_FILE=$SSL_CERT "$BIN_DIR/glance" --config "$GLANCE_CONFIG" >> $LOG_DIR/glance.log 2>&1
