#!/data/data/com.termux/files/usr/bin/sh
. $HOME/boot.env
. $HOME/glance/.env
sv check AdGuardHome || exit 1

cd $GLANCE_DIR
exec env SSL_CERT_FILE=$SSL_CERT ./glance --config glance.yml >> $LOG_DIR/glance.log 2>&1
