alerting:
  telegram:
    token: "$TELEGRAM_BOT_TOKEN"
    id: "$TELEGRAM_CHAT_ID"
    default-alert:
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 1

endpoints:
  - name: My-AdGuard-Home
    group: core
    url: "$ADGUARD_URL"
    interval: 10m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram

  - name: "SSL check $SSL_HOST_1"
    group: ssl
    url: "$SSL_URL_1" 
    interval: 6h
    client:
      dns-resolver: "udp://127.0.0.1:53" # dns rewrite to origin server
    conditions:
      - "[STATUS] == 200" 
      - "[CERTIFICATE_EXPIRATION] > 336h"
    alerts:
      - type: telegram
        failure-threshold: 2
      - type: telegram
        failure-threshold: 10

  - name: "SSL check $SSL_HOST_2"
    group: ssl
    url: "$SSL_URL_2" 
    interval: 6h
    client:
      dns-resolver: "udp://127.0.0.1:53" # dns rewrite to origin server
    conditions:
      - "[STATUS] == 200" 
      - "[CERTIFICATE_EXPIRATION] > 336h"
    alerts:
      - type: telegram
        failure-threshold: 2
      - type: telegram
        failure-threshold: 10

  - name: audiobookshelf
    group: services
    url: "http://127.0.0.1:13378/healthcheck"
    interval: 10m
    conditions:
      - "[STATUS] == 200"

  - name: glance
    group: services
    url: "http://127.0.0.1:8081"
    interval: 10m
    conditions:
      - "[STATUS] == 200"

  - name: memos
    group: services
    url: "http://127.0.0.1:5230"
    interval: 10m
    conditions:
      - "[STATUS] == 200"

  - name: beszel
    group: services
    url: "http://127.0.0.1:8090"
    interval: 10m
    conditions:
      - "[STATUS] == 200"

  - name: filebrowser
    group: services
    url: "http://127.0.0.1:8085"
    interval: 10m
    conditions:
      - "[STATUS] == 200"

  - name: qbittorrent
    group: services
    url: "http://127.0.0.1:8087"
    interval: 10m
    conditions:
      - "[STATUS] == 200"

external-endpoints:
  - name: "backup-memos"
    group: "maintenance"
    token: "$MEMOS_TOKEN"
    heartbeat:
      interval: 30h
    alerts:
      - type: telegram

  - name: "backup-system"
    group: "maintenance"
    token: "$SYSTEM_TOKEN"
    heartbeat:
      interval: 30h
    alerts:
      - type: telegram

  - name: "qingping"
    group: "iot"
    token: "$QINGPING_TOKEN"
    heartbeat:
      interval: 60m
    alerts:
      - type: telegram

ui:
  title: "Pixel Server Monitor"
  header: "Service Status"
