#!/data/data/com.termux/files/usr/bin/sh
set -a
. "$HOME/phone-server/.secrets/boot.env"
set +a

sv check AdGuardHome || exit 1

exec "$BIN_DIR/memos" --port $MEMOS_PORT --data $DATA_DIR/memos  > /dev/null 2>&1 # >> $LOG_DIR/memos.log 2>&1
