#!/data/data/com.termux/files/usr/bin/sh
set -a
. "$HOME/phone-server/.secrets/boot.env"
set +a

sv check $HOME/phone-server/services/adguard || exit 1

exec "$BIN_DIR/memos" --port $MEMOS_PORT --data $DATA_DIR/memos  >> $LOG_DIR/memos.log 2>&1
